name = "hidetaka-dev-workers"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# R2 bucket is optional - only needed if using incremental cache
# [[r2_buckets]]
# binding = "NEXT_INC_CACHE_R2_BUCKET"
# bucket_name = "cache"

[env.production]
vars = { MICROCMS_API_KEY = "" }

# 非本番環境（例: staging）
[env.staging]
vars = { MICROCMS_API_KEY = "" }

